### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by duanlaoyao** [liningtonlab/madbyte#18]
The MADByTE developed by your team has a good application, but there is a bug in use, how to solve it?
![image](https://github.com/liningtonlab/madbyte/assets/146741565/061b527a-f776-43aa-9c0a-83b38736ef1b)

**Comment by rlinington** [comment]
Hi @duanlaoyao we are now communicating about this offline so I am going to close this issue. Following the installation instructions in the tutorials (https://www.madbyte.org/tutorials) should resolve this.
