### ISSUE TITLE
Network constructin could not be completed due to an error

### ISSUE THREAD

**Issue by github-madhuri** [liningtonlab/madbyte#21]
When I am hitting generate network, an error appears saying Network constructin could not be completed due to an error.

![Image](https://github.com/user-attachments/assets/16e3ebd7-5c93-452f-bf21-d53932ba4085)

**Comment by shuxij** [comment]
Hi, have you solved this issue, I am running into the same issue using the sample data.

**Comment by Jmegan042** [comment]
@shuxij in this case it was a problem encountered with installing through anaconda navigator. If you also installed using anaconda navigator, please remove the environment and use the installation script. Otherwise, please explain any new issues with installation steps and steps taken to attempt to generate a network.

**Comment by shuxij** [comment]
@Jmegan042 Thanks for the reply. I removed and re-installed Madbyte. The same error message again. 

AttributeError: 'DataFrame' object has no attribute 'append'
 
ValueError: Inclusive has to be either string of 'both','left', 'right', or 'neither'.

Update, problem solved by Launching madbyte following instructions:
open a terminal and run the following commands:
o conda activate madbyte
▪ This tells anaconda to activate the MADByTE environment which houses all of the dependencies we just installed.
o python madbyte_gui.py
▪ This launches MADByTE!

**Comment by Jmegan042** [comment]
Hi @shuxij - this occurs because pandas > 2.0 is installed in the environment. We outline the environment in the environment.yml file, but sometimes if this is done without setting up a new environment, a newer version of pandas causes this issue.

**Comment by github-madhuri** [comment]
> Hi, have you solved this issue, I am running into the same issue using the sample data.

Yes, @Jmegan042 helped me solve this and I have managed to do it with sample data. It is working only with my Windows system, in case that helps.
