### ISSUE TITLE
MADByte Installation - enviroment 

### ISSUE THREAD

**Issue by RicardoMBorges** [liningtonlab/madbyte#5]
Hello hello,
I'm trying to install MADByTE to try it, but even though I have Anaconda 3, I'm using another (NMRfilter) environment. This is probably a question about the Anaconda 3, but can I just remove the environment I'm using to add MADByTE's without having to install the first environment again?
* can I have several environments installed?
Thanks!

**Comment by RicardoMBorges** [comment]
So, I tried and got the answer. Yes, I can. Now I only need to deactivate one and activate another, or the same. Thanks

**Comment by RicardoMBorges** [comment]
Ok. I failed. "Anaconda Python could not be found!
Please make sure you have Anaconda installed in the default location or report and issue to the MADByTE team". 
Could you help here?
Thanks

**Comment by Jmegan042** [comment]
Hi Ricardo, 

If you have anaconda installed in a custom location then you will have to launch and install via the command line. You can open Anaconda prompt (or another terminal) and navigate to the directory and try the following commands: 

To install: 

- conda env create -f environment.yml

Once complete, launch MADByTE by using: 

- conda activate madbyte (use this command to switch between anaconda environments)
- python madbyte_gui.py

and it should launch without performing the anaconda install check. 

There is a video tutorial [here](https://www.youtube.com/watch?v=51P5Rb-wUm8) of this process. 

Just as a quick note - the scripts check for Anaconda in one of two places. Either:

- %userprofile%\anaconda3
- %LocalAppData%\Continuum\anaconda3

Sometimes, Anaconda is installed in the directory C:\ProgramData\Anaconda3 - which the install and launch scripts do not check for. If this is the case, we can add this directory to the anaconda checking function.
