### ISSUE TITLE
TOCSY or HSQC-TOCSY

### ISSUE THREAD

**Issue by RicardoMBorges** [liningtonlab/madbyte#6]
Hello again,
I wonder (1) if it accepts HSQC-TOCSY data instead of TOCSY (or if there is a plan for it); and (2) would it run on peak lists as entrees? 

Thanks

**Comment by Jmegan042** [comment]
Hi Ricardo, 

MADByTE's initial analysis pipeline is to use explicit HSQC and TOCSY experiments and not the combined HSQC-TOCSY. This was done for a few reasons: 

- HSQC spectra give explicit assignments of the proton to the carbon, whereas the combined pulse sequence does not do this. This means that although we would be able to extract features to compare, the confidence in their comparison would fall drastically and not take the carbon resonances  into account - instead relying on proton only derived features resolved along the carbon axis. 
- MADByTE requires resonances to be present in both the HSQC and the TOCSY as a noise filtration. This means that if we used the combined pulse sequence, there would be no secondary check to ensure that a resonance is valid and not a product of noise or reconstruction (in the case of NUS data). 
- The sensitivity overall of the HSQC-TOCSY combined pulse sequence is markedly lower than that of a standard TOCSY, so derived spin systems may only represent the strongest of signals. 

However, the HSQC-TOCSY is a great experiment and may help to alleviate problems with data density in certain regions (such as the upfield regions). We had not previously planned on integrating this datatype into the analysis platform, but I would welcome some ideas as to how to do it. There is some great work on using HSQC-TOCSY features for fingerprinting (10.1021/acs.jnatprod.7b01063), but this was not the goal of MADByTE.
