### ISSUE TITLE
Clicking Help > Examples in GUI results in nothing

### ISSUE THREAD

**Issue by chanana** [liningtonlab/madbyte#8]
Upon clicking Help > Examples I get this error in the command line:

```bash
python madbyte_gui.py
MADByTE is loading...
Multithreading with maximum 16 threads
/bin/sh: Documentation/MADByTE_Quick_Start_Tutorial.pdf: Permission denied
```
Clicking Help > Documentation results in a similar error:

```bash
/bin/sh: Documentation/MADByTE_User_Manual.pdf: Permission denied
```

I'm running madbyte v1.2.0 on macOS Catalina (10.15.7) on a MacBook Pro (16" 2019)

**Comment by Jmegan042** [comment]
Hi Shaurya, 

Could you verify that in the MADByTE directory> Documentation the PDF files are there? 

It is possible that your permissions settings may be keeping MADByTE from accessing your default pdf program, which is used to launch the files. If this is the case, it would be helpful to know what program you use for PDF viewing so we can solve this.

**Comment by chanana** [comment]
They are indeed present and readable by user, group and others. The PDF viewer is the default "Preview" found on macOS.

A quick solution might be to amend the `Launch_Documentation` and `Launch_Example` functions in `madbyte_gui.py` as follows:

```python
subprocess.call(["open", os.path.join('Documentation','MADByTE_User_Manual.pdf')])
subprocess.call(["open", os.path.join('Documentation','MADByTE_Quick_Start_Tutorial.pdf')])
```

I modified my own `madbyte_gui.py` and tried it. It worked here. Not sure about Windows though. Would you like me to fork and submit a PR?

**Comment by Jmegan042** [comment]
That sounds like a great plan. After looking around, it seems the `subprocess.Popen` does have problems on Mac - great find.

**Comment by chanana** [comment]
I could potentially open a PR with my changes mentioned above but `pytest` still fails and produces the same errors regardless (#10).
